title: Soona Amhaz
description: |-
  <p></p>
  <p>Soona Amhaz is founder and GP of <a href="https://volt.capital">Volt Capital</a> a venture firm that focuses on pre-seed and seed companies in the digital assets space.</p>
  <p>Before starting Volt Capital, Soona launched <a href="https://www.tokendaily.co/">Token Daily</a>, a community of 20K+ builders, investors, and talent in the crypto space.
  Soona is an advisor to <a href="https://www.beondeck.com/">On Deck</a> and was a mentor at <a href="https://a16z.com/2019/12/11/announcing-crypto-startup-school-instructors/">the Andreessen Horowitz crypto startup school</a>.
  Soona hails from the University of Michigan School of Engineering. Go blue! </p>
logo: assets/img/headshot.png
theme: jekyll-theme-minimal
